name: Build & Push Docker Tag

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
jobs:
  docker-compose-build-push:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set up QEMU for ARM64 builds
        uses: docker/setup-qemu-action@v3
        with:
          platforms: arm64

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USERNAME }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build & push service api
        run: docker buildx build --platform linux/amd64,linux/arm64 -f src/MadWorldNL.OVHCloud.DynHost.Web/Dockerfile --tag ghcr.io/madworldnl/ovhcloud-dynhost:$GITHUB_REF_NAME --push .